# Generated by Django 4.2.27 on 2026-01-20 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0154_alter_problemtranslation_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemharness',
            name='run_student_main',
            field=models.BooleanField(default=False, help_text='If enabled, student code is the entry point; harness provides hidden APIs.', verbose_name='run student main'),
        ),
    ]
