# Generated by Django 4.2.27 on 2026-01-20 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0155_problemharness_run_student_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemharness',
            name='entry_point',
        ),
    ]
