# Generated by Django 4.2.27 on 2026-01-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0156_remove_problemharness_entry_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='classes',
            field=models.ManyToManyField(blank=True, help_text='If organization private, only these classes may see the problem.', to='judge.class', verbose_name='classes'),
        ),
    ]
