# Generated by Django 4.2.27 on 2026-02-05 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0157_problem_classes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('test_site', 'Shows in-progress development stuff'), ('totp', 'Edit TOTP settings'), ('impersonate_org', 'Impersonate members of organizations they admin'), ('impersonate_class', 'Impersonate members of classes they admin'), ('impersonate_contest', 'Impersonate participants of contests they author or curate')), 'verbose_name': 'user profile', 'verbose_name_plural': 'user profiles'},
        ),
    ]
