# Generated by Django 4.2.27 on 2026-02-06 01:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0158_alter_profile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='page',
            field=models.CharField(db_index=True, max_length=30, validators=[django.core.validators.RegexValidator('^[pcs]:[a-z0-9]+$|^b:\\d+$|^sub:\\d+$', 'Page code must be ^[pcs]:[a-z0-9]+$|^b:\\d+$|^sub:\\d+$')], verbose_name='associated page'),
        ),
        migrations.AlterField(
            model_name='commentlock',
            name='page',
            field=models.CharField(db_index=True, max_length=30, validators=[django.core.validators.RegexValidator('^[pcs]:[a-z0-9]+$|^b:\\d+$|^sub:\\d+$', 'Page code must be ^[pcs]:[a-z0-9]+$|^b:\\d+$|^sub:\\d+$')], verbose_name='associated page'),
        ),
    ]
