# Generated by Django 4.2.27 on 2026-03-12 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0159_alter_comment_page_alter_commentlock_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='ai_hints_enabled',
            field=models.BooleanField(default=False, help_text='Allow students to request AI-powered debugging hints on this problem.', verbose_name='enable AI hints'),
        ),
    ]
