# Generated by Django 4.2.27 on 2026-03-26 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0160_problem_ai_hints_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIHintLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('submission_result', models.CharField(blank=True, max_length=3, null=True)),
                ('submission_date', models.DateTimeField(blank=True, null=True)),
                ('success', models.BooleanField(db_index=True, default=False)),
                ('error_message', models.TextField(blank=True, default='')),
                ('hint_text', models.TextField(blank=True, default='')),
                ('prompt_tokens', models.IntegerField(blank=True, null=True)),
                ('completion_tokens', models.IntegerField(blank=True, null=True)),
                ('total_tokens', models.IntegerField(blank=True, null=True)),
                ('model_name', models.CharField(blank=True, default='', max_length=100)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_hint_logs', to='judge.problem')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_hint_logs', to='judge.submission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_hint_logs', to='judge.profile')),
            ],
            options={
                'verbose_name': 'AI hint log',
                'verbose_name_plural': 'AI hint logs',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['user', '-requested_at'], name='judge_aihin_user_id_4a3f04_idx'), models.Index(fields=['problem', '-requested_at'], name='judge_aihin_problem_0e73bb_idx')],
            },
        ),
    ]
